name: wxUiEditor builder

on: workflow_dispatch

jobs:

  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW32
          update: true
          install: >-
            git
            wget
            p7zip
          location: D:\

      - name: pre-build wxUiEditor
        shell: msys2 {0}
        id: prebuild
        run: ./prebuild.sh

      - name: build
        shell: pwsh
        id: build
        run: |
          cd D:\msys64\home\wxUiEditor\
          cmake -G "Visual Studio 17 2022" . -B build
          msys2 -c 'rm -rf "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.40.33807/bin/Hostx64/x64"'
          mkdir "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.40.33807/bin/Hostx64/x64"
          Copy-Item -Path "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.40.33807/bin/Hostx64/x86/*" -Destination "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.40.33807/bin/Hostx64/x64" -Recurse
          cmake --build build --config Release --target wxUiEditor

      - name: Prepare Release
        shell: msys2 {0}
        id: prerelease
        run: ./release.sh
      
      - name: release
        id: release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.prerelease.outputs.RELEASE_NAME }}
          release_name: ${{ steps.prerelease.outputs.RELEASE_NAME }}
          body: |
            This is wxUiEditor ${{ steps.prerelease.outputs.BUILD_DATE }} build.
          
      - name: upload
        id: upload
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: ${{ steps.prerelease.outputs.OUTPUT_BINARY }}
          asset_name: ${{ steps.prerelease.outputs.OUTPUT_NAME }}
          asset_content_type: application/x-7z-compressed
