name: wxUiEditor builder

on: workflow_dispatch

jobs:

  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW32
          update: true
          install: >-
            git
            wget
            p7zip
            cmake
            patch
            make
            unzip
          location: D:\

      - name: Download CMAKE
        shell: msys2 {0}
        run: ./cmake.sh
      
      - name: build wxUiEditor
        shell: pwsh
        id: build
        run: |
          $env:PATH="D:\temp\cmake-3.29.6-windows-i386\bin\;" + $env:PATH
          cd D:\temp
          git clone https://github.com/KeyWorksRW/wxUiEditor.git
          cd wxUiEditor\
          cmake -G "Visual Studio 17 2022" . -B build -A x86
          # -D CMAKE_CXX_COMPILER="/c/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.40.33807/bin/Hostx64/x64/cl.exe" -D CMAKE_C_COMPILER="/c/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.40.33807/bin/Hostx64/x64/cl.exe"
          cmake --build build --config Release --target wxUiEditor

      - name: release
        id: release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.build.outputs.RELEASE_NAME }}
          release_name: ${{ steps.build.outputs.RELEASE_NAME }}
          body: |
            This is wxUiEditor ${{ steps.build.outputs.BUILD_DATE }} build.
          
      - name: upload
        id: upload
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: ${{ steps.build.outputs.OUTPUT_BINARY }}
          asset_name: ${{ steps.build.outputs.OUTPUT_NAME }}
          asset_content_type: application/x-7z-compressed
